# Generated by Django 5.2.7 on 2025-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='نام URL')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیح Meta')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='کلمات کلیدی')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['-created_at'],
            },
        ),
    ]
