# Generated by Django 5.2.7 on 2025-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('client_name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('client_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('client_phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('items', models.JSONField(default=list, verbose_name='آیتم\u200cها')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل')),
                ('deposit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='پیش\u200cپرداخت')),
                ('payment_method', models.CharField(choices=[('full', 'پرداخت کامل'), ('deposit', 'پیش\u200cپرداخت'), ('installment', 'اقساط')], default='full', max_length=20, verbose_name='روش پرداخت')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='تعداد اقساط')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه تراکنش')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
