# Generated by Django 5.2.7 on 2025-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('slug', models.SlugField(unique=True, verbose_name='نام URL')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(max_length=500, verbose_name='توضیح کوتاه')),
                ('thumbnail', models.ImageField(upload_to='portfolio/', verbose_name='تصویر کوچک')),
                ('images', models.JSONField(default=list, help_text='["image1.jpg", "image2.jpg"]')),
                ('services', models.JSONField(default=list, help_text='["Web Design", "Development"]')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='مشتری')),
                ('link', models.URLField(blank=True, verbose_name='لینک پروژه')),
                ('completion_date', models.DateField(verbose_name='تاریخ تکمیل')),
                ('featured', models.BooleanField(default=False, verbose_name='برجسته')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['-featured', 'order', '-completion_date'],
            },
        ),
    ]
