# Generated by Django 5.2.7 on 2025-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='نام URL')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح کوتاه')),
                ('icon', models.CharField(blank=True, help_text='نام آیکون (مثل: Zap)', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='تصویر')),
                ('plans', models.JSONField(default=dict, help_text='{"Basic": 500, "Standard": 1000}')),
                ('features', models.JSONField(default=list, help_text='["Feature 1", "Feature 2"]')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
