# Generated by Django 5.2.7 on 2025-10-19 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, verbose_name='شماره سفارش')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('stripe', 'Stripe')], max_length=20, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('refunded', 'بازگردانده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه تراکنش')),
                ('reference_id', models.CharField(blank=True, max_length=255, verbose_name='شناسه مرجع')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
